{
"spider":"https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1731682555989/fan.txt;md5;6c4ab3a9d232164c75534f9060506ee5",
"wallpaper":"https://深色壁纸.xxooo.cf/",
"sites":[
{"key":"豆豆","name":"豆瓣┃推荐","type":3,"api":"csp_DouDou","searchable":0,"quickSearch":0,"filterable":0},
{"key":"文采","name":"推荐┃秒播","type":3,"api":"csp_Jpys","playerType":2,"searchable":1,"quickSearch":1,"changeable":1},
 {
      "key": "天天",
      "name": "天天┃多线",
      "type": 3,
      "api": "csp_TTian",
      "playerType": 2,
      "ext": "baHR0cDovL29wLnlzZHFqcy5jbg==",
      "jar": "https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1729754716332/qj.jar;md5;1c2663a32f99e9e488cb4777ba1ea73f"
    },
{
      "key": "saohuo",
      "name": "直连┃超清",
      "type": 3,
      "searchable": 1,
      "changeable": 0,
      "quickSearch": 1,
      "playerType": "2",
      "jar": "https://fs-im-kefu.7moor-fs1.com/29397395/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1704761840381/c (1).txt;md5;bb155c3f0133bbce4756ad52003f5968",
      "api": "csp_XBPQ",
      "ext": {
        "嗅探词": ".m3u8#.mp4#.m3u8?#freeok.mp4",
        "分类url": "https://shdy2.com/list/{cateId}-{catePg}.html;;vr1au0",
        "分类": "电影$1#电视剧$2#韩剧$22#美剧$23#动漫$4",
        "数组二次截取": "class=\"v_list\">&&</ul>",
        "数组": "\"v_img\"&&/div>",
        "标题": "title=\"&&\"",
        "副标题": "v_note\"&&</div",
        "跳转播放链接": "<iframe*src=\"&&\"",
        "二次跳转播放链接": "https://hhjx.hhplayer.com/api.php;post;url=+var url*\"&&\"+&t=+var t*\"&&\"+&key=+var key*\"&&\"+&act=0+&play=1",
        "三次跳转播放链接": "\"url\"*\"&&\""
      }
    },
{"key":"贱贱","name":"推荐┃超清","type":3,"searchable":1,"quickSearch":1,"changeable":1,"playerType":"1","api":"https://ghproxy.cn/https://raw.githubusercontent.com/fantaiying7/EXT/refs/heads/main/drpy2.min.js","ext":"https://ghproxy.cn/https://raw.githubusercontent.com/fantaiying7/EXT/refs/heads/main/jp.js"},
{"key":"新6V","name":"推荐┃磁力","type":3,"api":"csp_SixV","searchable":1,"quickSearch":1,"changeable":0,"ext":"https://www.xb6v.com/"},
{"key":"苹果","name":"苹果┃不卡","type":3,"api":"csp_LiteApple","searchable":1,"quickSearch":1,"changeable":1},
{"key":"Auete","name":"奥特┃无广","type":3,"api":"csp_Auete","timeout":15,"searchable":1,"quickSearch":1,"changeable":1,"ext":"https://auete.com/"},
{"key":"926看球","name":"⚽926┃看球","type":3,"api":"csp_kanqiu926","searchable":0,"changeable":0,"style":{"type":"list"}},
{"key":"88js","name":"⚽88┃看球","type":3,"api":"https://notabug.org/fantaiying/ext/raw/main/drpy2.min.js","ext":"https://notabug.org/fantaiying/ext/raw/main/88看球.js","style":{"type":"list"},
"searchable":0,"quickSearch":0,"changeable":0},
{"key":"310js","name":"⚽310┃看球","type":3,"api":"https://notabug.org/fantaiying/ext/raw/main/drpy2.min.js","ext":"https://notabug.org/fantaiying/ext/raw/main/310直播.js","style":{"type":"list"},
"searchable":0,"quickSearch":0,"changeable":0},
{"key":"Jrsjs","name":"⚽Jrs┃球迷","type":3,"api":"https://notabug.org/fantaiying/ext/raw/main/drpy2.min.js","ext":"https://notabug.org/fantaiying/ext/raw/main/jrk.js","style":{"type":"list"},
"searchable":0,"quickSearch":0,"changeable":0},
{"key":"有声小说js","name":"🎧有声┃小说","type":3,"api":"https://notabug.org/fantaiying/ext/raw/main/drpy2.min.js","ext":"https://notabug.org/fantaiying/ext/raw/main/有声小说吧.js","style":{"type":"rect","ratio":1},
"searchable":0,"quickSearch":0,"changeable":0},
{"key":"Aid","name":"🚑急救┃教学","type":3,"api":"csp_FirstAid","searchable":0,"quickSearch":0,"changeable":0,"style":{"type":"rect","ratio":3.8}},
{"key":"push_agent","name":"🛴手机┃推送","type":3,"api":"csp_Push","searchable":0,"quickSearch":0,"ext":{"Cloud-drive":"tvfan/Cloud-drive.txt","from":"4k|auto"}},
{"key":"dr_兔小贝","name":"📚儿童┃启蒙","type":3,"api":"https://notabug.org/fantaiying/ext/raw/main/drpy2.min.js","ext":"https://notabug.org/fantaiying/ext/raw/main/%E5%85%94%E5%B0%8F%E8%B4%9D.js","style":{"type":"rect","ratio":1.597},
"searchable":0,"quickSearch":0,"changeable":0},
{"key":"少儿教育","name":"📚少儿┃教育","type":3,"api":"csp_Bili","style":{"type":"rect","ratio":1.597},
"searchable":0,"quickSearch":0,"changeable":0,"ext":{"json":"https://notabug.org/fantaiying/ext/raw/main/少儿教育.json"}},
{"key":"小学课堂","name":"📚小学┃课堂","type":3,"api":"csp_Bili","style":{"type":"rect","ratio":1.597},
"searchable":0,"quickSearch":0,"changeable":0,"ext":{"json":"https://notabug.org/fantaiying/ext/raw/main/小学课堂.json"}},
{"key":"初中课堂","name":"📚初中┃课堂","type":3,"api":"csp_Bili","style":{"type":"rect","ratio":1.597},
"searchable":0,"quickSearch":0,"changeable":0,"ext":{"json":"https://notabug.org/fantaiying/ext/raw/main/初中课堂.json"}},
{"key":"高中教育","name":"📚高中┃课堂","type":3,"api":"csp_Bili","style":{"type":"rect","ratio":1.597},
"searchable":0,"quickSearch":0,"changeable":0,"ext":{"json":"https://notabug.org/fantaiying/ext/raw/main/高中课堂.json"}},
{"key":"fan","name":"导航www.饭太硬.com","type":3,"api":"csp_XPath","searchable":1,"quickSearch":0,"changeable":0},
{"key":"cc","name":"请勿相信视频中广告","type":3,"api":"csp_XPath","searchable":1,"quickSearch":0,"changeable":0}
],
"logo":"https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1716545739254/fc1b89e152cd4aa28d295107cb6c56c9.gif",
"lives":[
{"name":"全球TV","type":0,"url":"http://gdp.ink/down.php/7173594b57713a914514192b306eaf76.jpg","playerType":1,"epg":"http://diyp5.112114.xyz/?ch={name}&date={date}","logo":"http://diyp5.112114.xyz/{name}.png"},
{"name":"秘密花园","type":0,"url":"http://pan.losfer.cn/down.php/99725ee483e175d73fd5057e4fe4c703.jpg","playerType":1},
{"name":"IPV6","type":0,"url":"http://zykjtv01.usa7.345888.xyz.cdn.cloudflare.net/ipv6.txt","playerType":1}]}